apiVersion: v1
kind: Service
metadata:
  labels:
    app: mask-detection
  name: mask-detection
spec:
  ports:
  - name: "8554"
    port: 8554
  selector:
    app: ar
    tier: frontend
  type: LoadBalancer
